namespace winui
{
    [default_interface]
    runtimeclass BlockLogPage : Microsoft.UI.Xaml.Controls.Page
    {
        BlockLogPage();
        void Refresh_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void Clear_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void MarkPopup_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void MarkNotPopup_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ExportSamples_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void AddToBlacklist_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void AddToWhitelist_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void Filter_Changed(Object sender, Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs args);
        void Search_Changed(Object sender, Microsoft.UI.Xaml.Controls.TextChangedEventArgs args);
        void OnLogListLoaded(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void NewLogJumpButton_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}