namespace winui
{
    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        HomePage();
        void GlowPointerEntered(Object sender, Microsoft.UI.Xaml.Input.PointerRoutedEventArgs args);
        void GlowPointerMoved(Object sender, Microsoft.UI.Xaml.Input.PointerRoutedEventArgs args);
        void GlowPointerExited(Object sender, Microsoft.UI.Xaml.Input.PointerRoutedEventArgs args);
    }
}