namespace winui
{
    [default_interface]
    runtimeclass HomePage : Microsoft.UI.Xaml.Controls.Page
    {
        HomePage();

        void RootPointerMoved(Object sender, Microsoft.UI.Xaml.Input.PointerRoutedEventArgs args);
        void RootPointerExited(Object sender, Microsoft.UI.Xaml.Input.PointerRoutedEventArgs args);
        void GoToBlocker_Tapped(Object sender, Microsoft.UI.Xaml.Input.TappedRoutedEventArgs args);
    }
}