namespace winui
{
    [default_interface]
    runtimeclass PopupBlockerPage : Microsoft.UI.Xaml.Controls.Page
    {
        PopupBlockerPage();
        void EnableToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void AddRule_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void DeleteRule_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void Pick_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void SearchInput_TextChanged(Object sender, Microsoft.UI.Xaml.Controls.TextChangedEventArgs args);
        void CommunityRulesToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void RetryFetchButton_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void EditRule_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}