namespace winui
{
    [default_interface]
    runtimeclass PrivacyPage : Microsoft.UI.Xaml.Controls.Page
    {
        PrivacyPage();
        void BackButton_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}
