namespace winui
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        void ThemeComboBox_SelectionChanged(Object sender, Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs args);
    }
}