namespace winui
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        void ThemeComboBox_SelectionChanged(Object sender, Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs args);
        void LicenseLink_Click(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void ForceBlockToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void HeuristicModeCombo_SelectionChanged(Object sender, Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs args);
        void VerboseLogToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void AutoStartToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
        void MLHeuristicToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void ToastNotifyToggle_Toggled(Object sender, Microsoft.UI.Xaml.RoutedEventArgs args);
    }
}